DRG: Move Dragon Sight and Lance Charge to core BuffWindow Module
xivanalysis/xivanalysis pull request #1063
Opened 2020-12-17 19:49 UTC by ebshimizu

Removed (most) class specific logic for Dragon Sight and Lance Charge buff windows.

- Core: Modified to include a `secondaryBuffStatus` parameter because DRG has a separate id for a solo Dragon Sight. Existing modules are unaffected and should function as before with no modifications required.
- Deleted `drgBuffWindow` module and set LC/DS modules to inherit from core `BuffWindow`
- Suggestions re-written for both windows to highlight the specific things that we're looking for in each window. Previously, the suggestion just told people to use DS/LC any time except after a Chaos Thrust or Full Thrust and did not explain why. Now, the suggestion and the table highlights the GCDs that we're expecting to be within the window instead of just saying "bad start."

Review Notes
- Please advise on changes to core and if there's a better way to accommodate DRG's split buff ids
- Set expected uses for FC/WT to 1. It's definitely possible to get 2 but I'm not sure it's a hard requirement? 1 FT/CT definitely is.

Table Preview
![image](https://user-images.githubusercontent.com/777098/102535805-bca23e00-4076-11eb-9660-a605c1a437c5.png)

Suggestion Preview
![image](https://user-images.githubusercontent.com/777098/102535963-ef4c3680-4076-11eb-929b-7426194f699f.png)

2020-12-21 18:49 UTC, ebshimizu commented
PR updated to include notes on the cause of truncated Dragon Sight windows. The buff disappears if your partner dies, of if you die. In the event of partner death, the expected GCDs and tracked actions are adjusted to not penalize the DRG (you cannot control your partner). If the DRG dies, no adjustments to expected actions are performed (you can control yourself).

implementation note for this: the notes column is set to appear only if a truncated window shows up, though this is done somewhat awkwardly through relying on a helper being called before the table is output. This could probably be addressed better by a modification to the core module that would only show the notes header if at least one window returns something that's not undefined.

2020-12-28 22:31 UTC, AzariahAeroborn requested changes

2020-12-28 22:31 UTC, AzariahAeroborn commented on src/parser/core/modules/BuffWindow.tsx
> +		if ((!this.buffStatus || event.ability.guid !== this.buffStatus.id) &&
Per discussion [on Discord](https://discord.com/channels/441414116914233364/441424599310270464/793185644699582494) - we should refactor this to use the utilities class method `ensureArray` and change buffStatus to accept `Status | Status[]`

I POC'd this with:
```
	private onApplyBuff(event: BuffEvent) {
		if (!this.buffIsTracked(event.ability.guid)) {
			return
		}

		this.startNewBuffWindow(event.timestamp)
	}

	private onRemoveBuff(event: BuffEvent) {
		if (!this.buffIsTracked(event.ability.guid)) {
			return
		}

		if (this.activeBuffWindow) {
			this.activeBuffWindow.end = event.timestamp
		}
	}

	protected buffIsTracked(buffId: number) {
		let buffStatusArray = ensureArray(this.buffStatus)
		return buffStatusArray.some(bs => bs.id == buffId)
	}

	protected trackedBuffDuration() {
		let buffStatusArray = ensureArray(this.buffStatus)
		return buffStatusArray[0].duration
	}
```

and it seemed to WOMM.

2020-12-28 22:33 UTC, AzariahAeroborn approved these changes

2020-12-28 22:33 UTC, merged