upgrade Weaving to Analyzer, port dependencies
xivanalysis/xivanalysis pull request #1212
Opened 2021-06-17 01:41 UTC by AzariahAeroborn

2021-08-10 16:47 UTC, nonowazu requested changes
As you said, lift and shift, but I figured we could make 1-2 things slightly better during the cleanup part.

2021-08-10 16:47 UTC, nonowazu commented on src/parser/core/modules/Weaving.tsx
> +	protected suggestionContent: ReactNode = <Trans id="core.weaving.content">
I'd suggest a comment much like buffwindow that lets people know they can override this – this is me suggesting something non-core dev-facing though.

2021-08-10 16:47 UTC, nonowazu commented on src/parser/core/modules/Weaving.tsx
> +	protected suggestionIcon: string = 'https://xivapi.com/i/001000/001785.png' // WVR Focused Synth
might as well go ahead and replace this with a `this.data` call. Also a comment letting people know they can override this would be nice.

2021-09-15 13:57 UTC, ackwell approved these changes

2021-09-15 13:57 UTC, merged