[PLD] Atonement Checklist
xivanalysis/xivanalysis pull request #1224
Opened 2021-08-13 04:15 UTC by Rjb99

In an attempt to make XIVA better at telling me I'm bad, I've added a Atonement Checklist item.
Current target is 100% usage of Atonement. I know of no reason to drop any stacks for a dps gain.

2021-08-13 05:06 UTC, Rjb99 commented
For the record. I now hate Visual Studio. Despite being on different branches my SAM i18n files mixed in with these and caused it to constantly fail.

2021-08-13 07:08 UTC, Rjb99 commented
Changed Rule to TieredRule
100% = success
99% to 95% = warn
94% to 0% = Red/bad

2021-08-14 00:48 UTC, nonowazu requested changes
I think it looks good personally, just a few minor nits.

2021-08-14 00:48 UTC, nonowazu commented on src/parser/jobs/pld/modules/Atonement.tsx
> +import {dependency} from '../../../core/Injectable'
personal nit, maybe change this to:

```ts
import {dependency} from 'parser/core/Injectable'
```

2021-08-14 00:48 UTC, nonowazu commented on src/parser/jobs/pld/modules/Atonement.tsx
> +		}, this.onAtonement)
weird personal thought, wouldn't this be better?

```ts

		this.addEventHook({
			type: 'action',
			source: this.parser.actor.id,
			action: this.data.actions.ATONEMENT.id,
		}, () => this.actions++)
```

it'd save you a whole function, anyway?

Same with the `onRoyal` part

2021-08-14 00:48 UTC, nonowazu commented on src/parser/jobs/pld/modules/Atonement.tsx
> +			name: 'Use Atonements Generated By Royal Authority',
Shouldn't this have a `Trans` tag?

2021-08-16 03:51 UTC, Rjb99 commented
Fixed Nono's Nits.

I think this is good to merge now.

2021-08-18 01:45 UTC, AkairyuGestalter approved these changes

2021-08-18 01:46 UTC, merged