feat: add helpers for matching actions or statuses on the cause property
xivanalysis/xivanalysis pull request #1298
Opened 2021-10-30 16:11 UTC by AzariahAeroborn

2021-10-31 01:57 UTC, AkairyuGestalter requested changes

2021-10-31 11:14 UTC, ayyaruq commented
Does this really belong in Data rather than say in filters itself? Data is about the access to layers, not really the event filtering system. Not sure about `matchStatusId` and `matchActionId` either.

2021-11-01 20:05 UTC, AzariahAeroborn commented on src/parser/jobs/dnc/modules/DirtyDancing.tsx
> -	private danceMoveIds = DANCE_MOVES.map(key => this.data.actions[key].id)
Ah, yeah, I think I mentally processed this as occurring in onComplete and thus only happening once.

2021-11-01 20:06 UTC, AzariahAeroborn commented
> Does this really belong in Data rather than say in filters itself? Data is about the access to layers, not really the event filtering system. Not sure about `matchStatusId` and `matchActionId` either.

Filter is a set of utility functions, not an analyser, so it doesn't have access to the data system to be able to match on IDs.  Also, the others were pre-existing conditions and it was specifically recommended that I put the new ones next to them 🤷

2021-11-02 13:45 UTC, ackwell approved these changes

2021-11-02 13:46 UTC, merged