BLM -  Port Gauge to core
xivanalysis/xivanalysis pull request #1329
Opened 2021-11-07 01:06 UTC by AkairyuGestalter

Pls2ignore stupid revision history. Changes herein:
- Fixes TimerGauge graphing output (linear curve, data array construction, tooltip 'current' value calculation)
- Adds Dowtime window API to TimerGauge to find out when the timer was allowed to expire
- Port BLM's Gauge to Core & assorted coding style cleanup
- Adds display for BLM's AF/UI/Polyglot timers
- Adds tracking/core hooks for statuses that pause TimerGauges (Currently just TEA's timestop, fixes all the BrokenLogs we get from BLM Gauge thinking AF/UI/Polyglot dropped)
- Due to above, and the likelihood that just about all Gauges will need it, the Data dependency for Gauges is now protected in Core, instead of private in subclasses

2021-11-09 05:33 UTC, ayyaruq reviewed
A few points here, not marking as required. Since you fab the gauge events, maybe consider having a separate module hook that to manage speed changes, instead of having all the value checks in here. Not sure how complex that would be tho.

With the `onCast` function, you might find it simpler to check the event type rather than if the field is in it, since we know an Action event always has an action member, while a cause might have an action. Could be clearer to read. You already type check slightly further down the function anyway.

I'd also consider adding a getter to CounterGauge as a boolean for if the gauge is capped, at least for a given time. Would simplify a lot of your checks since you can just `this.astralFireGauge.capped` rather than comparing against max everywhere. Give it another name if need be.

2021-11-09 05:33 UTC, ayyaruq commented on src/parser/jobs/blm/modules/Gauge.tsx
> +const FIRE_COLOR = Color.rgb(210, 62, 38)
Can convert these to hex and use the string form to avoid the linter override.

2021-11-09 05:33 UTC, ayyaruq commented on src/parser/jobs/blm/modules/Gauge.tsx
>  const MAX_POLYGLOT_STACKS = 2
Can consider renaming these imo. Lead with ASTRAL_UMBRAL, ENOCHIAN, POLYGLOT, etc and use the suffix to indicate what it's used for. Mostly just nicer for intellisense, but it's easier to read.

2021-11-09 05:33 UTC, ayyaruq commented on src/parser/jobs/blm/modules/Gauge.tsx
> +	}))
I'd likely just track this as a boolean rather than gauge. It's either on or off.

2021-11-09 05:33 UTC, ayyaruq commented on src/parser/jobs/blm/modules/Gauge.tsx
> +				}).filter((uta) => Math.max(0, uta.end - uta.start) >= ASTRAL_UMBRAL_DURATION).length > 0) {
Might not need the extra parentheses on uta here.

2021-11-12 23:23 UTC, AzariahAeroborn requested changes

2021-11-12 23:23 UTC, AzariahAeroborn commented on src/parser/core/modules/Gauge/TimerGauge.ts
> +	private internalDowntime(start = this.parser.pull.timestamp, end = this.parser.currentEpochTimestamp) {
I know that "downtime" makes sense when talking about time a timer based job gauge isn't running, but the term is also overloaded with unable to act time, and we're going to need to be referring to both when computing how long the job gauge wasn't running for that it should have been, so is there an alternate term we could use here to describe "time the gauge wasn't running or paused"?

2021-11-12 23:23 UTC, AzariahAeroborn commented on src/parser/core/modules/Gauge/TimerGauge.ts
> +	public getDowntime(start = this.parser.pull.timestamp, end = this.parser.currentEpochTimestamp) {
This needs to consider and exclude UTA time from the total gauge downtime.

2021-11-12 23:23 UTC, AzariahAeroborn commented on src/parser/core/modules/Gauge/Gauge.tsx
>  	}
I don't see any users being updated in this PR to use these - what's the reasoning behind exposing them?  If we are going to expose these, we should move the pauseGeneration infrastructure out to specifically the dancer gauges and make that behavior an implementation detail of gauge modules that need it.

2021-11-12 23:23 UTC, AzariahAeroborn commented on src/parser/core/modules/Gauge/TimerGauge.ts
> +			} else if (length > 0) {
I commented a little more on discord about an alternate approach for history tracking that would streamline a lot of this graph generation code, but if we keep the current approach, we don't need this if (length > 0) here - no harm done by adding a 0 at the timestamp of the first generation event.

2021-11-13 17:31 UTC, AzariahAeroborn approved these changes

2021-11-13 17:32 UTC, merged