Updated ACTIONS and STATUSES with new PLD information.
xivanalysis/xivanalysis pull request #1415
Opened 2021-12-17 04:54 UTC by Dynme

Adds new abilities and status effects at 80+, updates potencies and durations of various skills.

2021-12-17 06:48 UTC, ayyaruq approved these changes
Data looks good, I'll note that PLD doesn't seem to use potency data anywhere so it's probably not even necessary and adds extra maintenance effort in future patch layers.

2021-12-18 00:14 UTC, AzariahAeroborn requested changes

2021-12-18 00:14 UTC, AzariahAeroborn commented on src/data/ACTIONS/root/PLD.ts
> +		statusesApplied: ['INTERVENTION', 'KNIGHTS_RESOLVE', 'KNIGHTS_BENEDICTION'],
Having multiple actions with the same `statusesApplied` may result in incorrect actions being synthesized if the actions are being used pre-pull.  If either Intervention or Holy Sheltron can reasonably be used pre-pull, we should exclude these duplicated statusesApplied (and specifically for Intervention, we're probably going to need to add some special handling to synthesize an action by the PLD for a status applied to another actor).

At least as of now, `statusesApplied` is only used for that data fix-up process of synthesizing pre-pull actions, so it's not super critical to keep the data exactly in line with the actual job actions.

2021-12-18 13:53 UTC, AzariahAeroborn approved these changes

2021-12-18 13:53 UTC, merged