[SAM] Restore Gauge  + Fuko Bug Fix
xivanalysis/xivanalysis pull request #1486
Opened 2022-01-01 03:18 UTC by Rjb99

This restores all of SAM's Sen and Kenki Gauge to the Analysis.
Also includes a "Bugfix" to Fuga/Fuko by erasing Fuga from the pages of history

2022-01-03 04:27 UTC, AzariahAeroborn requested changes

2022-01-03 04:27 UTC, AzariahAeroborn commented on src/parser/jobs/sam/modules/Sen.tsx
> +		if ((typeof lastSenState === 'undefined') || (lastSenState.isDone === true)) {
```suggestion
		if ((lastSenState == null) || (lastSenState.isDone === true)) {
```
Please use == null (or != as necessary) when checking for null/undefined values.

2022-01-03 04:27 UTC, AzariahAeroborn commented on src/parser/jobs/sam/modules/Kenki/Kenki.tsx
> +		if (this.damageHook !== undefined) {
```suggestion
		if (this.damageHook != null) {
```

2022-01-03 04:27 UTC, AzariahAeroborn commented on src/parser/jobs/sam/modules/Kenki/Kenki.tsx
> +		if (modifier !== undefined)	{
```suggestion
		if (modifier != null)	{
```

2022-01-03 04:27 UTC, AzariahAeroborn commented on src/parser/jobs/sam/modules/index.js
> +// import {Higanbana} from './Higanbana'
commented out so it doesn't really matter here, but this should still be above Interrupts to maintain alphabetical order of imports

2022-01-09 17:14 UTC, Rjb99 commented
Requested Changes made. Import order will be fixed in the next PR with Higanabana

2022-01-09 22:11 UTC, AzariahAeroborn approved these changes

2022-01-09 22:11 UTC, merged