Add positionals to XIVA
xivanalysis/xivanalysis pull request #1603
Opened 2022-02-01 23:43 UTC by eatmorehufu

- Adds new positional Checklist entry for all melees
- Adds new positional module for all melees

Screenshots of the module and checklist for good/bad results: https://imgur.com/a/VwOlldS

2022-02-07 21:54 UTC, AzariahAeroborn requested changes

2022-02-07 21:54 UTC, AzariahAeroborn commented on src/reportSources/legacyFflogs/eventAdapter/translate.ts
> +		const bonusPercent = event.bonusPercent || 0
```suggestion
		const bonusPercent = event.bonusPercent ?? 0
```
We prefer ?? for nullish coalescence, rather than relying on falsey behavior.

2022-02-07 21:54 UTC, AzariahAeroborn commented on src/reportSources/legacyFflogs/eventAdapter/translate.ts
> +		const bonusPercent = event.bonusPercent || 0
```suggestion
		const bonusPercent = event.bonusPercent ?? 0
```
We prefer ?? for nullish coalescence, rather than relying on falsey behavior.

2022-02-07 21:54 UTC, AzariahAeroborn commented on src/parser/core/modules/Positionals.tsx
> +				.cause(filter<Cause>().action(oneOf(this.positionals.map(positional => positional.action.id)))), this.onCast)
```suggestion
				.cause(this.data.matchCauseActionId(this.positionals.map(positional => positional.action.id))), this.onCast)
```

You can shorten up the boilerplate with the matchCauseActionId or matchCauseAction helpers in the Data module.  Personally, I'd prefer the matchCauseAction helper, and change the signature of Positional.action to expect an ActionKey -- then implementers could just reference `'DEMOLISH'` or whatever skill name, without needing to do the this.data.actions boilerplate dance, but the Id helper and your current interface will work as well.

2022-02-07 21:54 UTC, AzariahAeroborn commented on src/parser/core/modules/Positionals.tsx
> +		if (!action) {
```suggestion
		if (action == null) {
```
Style guide: We prefer explicit == null checks for null/undefined guards, rather than relying on falsey behavior

2022-02-07 21:54 UTC, AzariahAeroborn commented on src/parser/core/modules/Positionals.tsx
> +		if (!positional) {
```suggestion
		if (positional == null) {
```
Style guide: We prefer explicit == null checks for null/undefined guards, rather than relying on falsey behavior

2022-02-08 02:03 UTC, eatmorehufu commented
Messing around with an unintended merge.

2022-02-08 23:53 UTC, AzariahAeroborn approved these changes

2022-02-12 14:51 UTC, merged