Split out BlitzEvaluator from RoF
xivanalysis/xivanalysis pull request #1615
Opened 2022-02-10 18:28 UTC by Malpp

Also rename skills to actions

2022-02-11 00:56 UTC, hintxiv requested changes
Looks good, definitely improves readability for the RoF module.

2022-02-11 00:56 UTC, hintxiv commented on src/parser/jobs/mnk/modules/evaluators/BlitzEvaluator.tsx
> +}
Since there's only one parameter here, we can save a few lines of code by getting rid of this interface and having the constructor accept `blitzActions: Array<Action['id']>` directly.

2022-02-11 01:08 UTC, ayyaruq commented on src/parser/jobs/mnk/modules/evaluators/BlitzEvaluator.tsx
> +}
That's bad design, I requested a change from that approach to this one in the previous PR.

2022-02-11 01:23 UTC, hintxiv approved these changes

2022-02-12 02:53 UTC, ayyaruq approved these changes
Nicely done.

2022-02-12 02:56 UTC, merged