Change embolden to use RaidBuffWIndow.
xivanalysis/xivanalysis pull request #1639
Opened 2022-02-18 05:20 UTC by eatmorehufu

This should be a no-op to the existing Embolden module functionality. The physical skills are still ignored in the rotation window.

2022-02-19 06:20 UTC, eatmorehufu commented
Added Searing Light to this PR as well.

2022-02-19 19:11 UTC, KelosPelmand requested changes
Please have PlayersBuffedEvaluator create its own suggestions like the other evaluators do.

I did not check Embolden at all, but it turns out the the Searing Light one doesn't actually work in some cases.  Due to the buff being pet sourced, it is possible for another player to get the buff before you do, which results in them not being counted as buffed in the players buffed count.  (See the 6:18 window in https://xivanalysis.com/fflogs/gAbwHX4BY9rC7n6d/7/7).

I think it would be better to leave the SL file not using BuffWindow rather than try to add a bunch of special hook points to BuffWindow just to make the one existing pet sourced buff work with it.

2022-02-19 19:11 UTC, KelosPelmand commented on src/parser/core/modules/ActionWindow/evaluators/PlayersBuffedEvaluator.tsx
> +	suggestion: (windows: Array<HistoryEntry<EvaluatedAction[]>>) => Suggestion | undefined
This is not the right pattern for suggestion generation.  (You are requiring duplicate code in all the implementors.)  As with other evaluators, TrackedBuffOpts should have

```
suggestionIcon: string
suggestionContent: JSX.Element
suggestionWindowName: JSX.Element
```

and do the suggestion logic itself.  If some jobs with raid buffs strongly object to having a suggestion, add a `suppressSuggestion: boolean` that defaults to false and check that in the suggest method of PlayersBuffedEvaluator.  If classes being moved to RaidBuffWindow just didn't have a suggestion, I would guess it was more that they didn't think about it than that they didn't do it.

2022-02-19 19:11 UTC, KelosPelmand commented on src/parser/core/modules/ActionWindow/windows/ActionWindow.tsx
> +	protected onComplete() {
This should return to private after making PlayersBuffedEvaluator do it's own suggestions.

```suggestion
	private onComplete() {
```

2022-02-19 19:11 UTC, KelosPelmand commented on src/parser/core/modules/ActionWindow/windows/ActionWindow.tsx
> +	@dependency protected suggestions!: Suggestions
This should return to private after making PlayersBuffedEvaluator do it's own suggestions.

```suggestion
	@dependency private suggestions!: Suggestions
```

2022-02-20 04:50 UTC, eatmorehufu commented
I reverted the SL changes to keep this PR simple with just RDM changes. I'll add a followup for passing through suggestions later.

2022-03-03 17:58 UTC, Cephid commented
If Kelos is happy with the fixes addressing the original concerns I'm fine with this.  The output is identical to what we had, and this removes maintenance further down the road.

2022-03-15 15:19 UTC, ayyaruq approved these changes
This should have a code style pass at some point.

2022-03-15 15:19 UTC, merged