Riddle of Wind statistic
xivanalysis/xivanalysis pull request #1645
Opened 2022-02-21 02:37 UTC by Malpp

Bad log:
![image](https://user-images.githubusercontent.com/17149559/154879751-cb7a69d3-e2c3-4535-a502-90748e51e7cd.png)

Perfect play:
![image](https://user-images.githubusercontent.com/17149559/154879801-a169d3b6-2950-4c88-9b9d-3d044c25668c.png)

Info:
![image](https://user-images.githubusercontent.com/17149559/154879847-73c7d0fc-a71b-4dbf-b7fb-c2441fb107cf.png)

2022-02-21 03:10 UTC, ayyaruq requested changes
Mostly wanna tighten up some string formatting, but I feel like BuffWindow is severely overkill here since we use nothing it provides but still have all the overhead. This module would be smaller as just a native analyser since there's really not that much you need to capture.

2022-02-21 03:10 UTC, ayyaruq commented on src/parser/jobs/mnk/modules/DISPLAY_ORDER.ts
> +	DEMOLISH: 8,
Not sure why this needs to happen, statistic boxes are fixed locations and without any suggestions there's nothing to display so the display order for RoW isn't used. Generally also prefer to not re-order this file.

2022-02-21 03:10 UTC, ayyaruq commented on src/parser/jobs/mnk/modules/RiddleOfWind.tsx
> +	static override displayOrder = DISPLAY_ORDER.RIDDLE_OF_WIND
Neither of these get used.

2022-02-21 03:10 UTC, ayyaruq commented on src/parser/jobs/mnk/modules/RiddleOfWind.tsx
> +	@dependency globalCooldown!: GlobalCooldown
This isn't used anywhere, can kill the import for it as well.

2022-02-21 03:10 UTC, ayyaruq commented on src/parser/jobs/mnk/modules/RiddleOfWind.tsx
> +	private riddleOfWind: ActionRoot['RIDDLE_OF_WIND'] = this.data.actions.RIDDLE_OF_WIND
This doesn't get used anywhere.

2022-02-21 03:10 UTC, ayyaruq commented on src/parser/jobs/mnk/modules/RiddleOfWind.tsx
> +				able get full uptime on the boss. This is a DPS loss due to missing auto attacks.
```suggestion
				Missing auto attacks during <ActionLink action="RIDDLE_OF_WIND"/> means you were not able get full uptime on the boss. This is a DPS loss due to missing auto attacks.
```

2022-02-21 03:10 UTC, ayyaruq commented on src/parser/jobs/mnk/modules/RiddleOfWind.tsx
> +				Auto attacks hits
```suggestion
				Auto Attack Hits
```

2022-02-21 03:10 UTC, ayyaruq commented on src/parser/jobs/mnk/modules/RiddleOfWind.tsx
> +const MAX_ATTACKS_PER_ROW_WINDOW = 15
No need to limit width so much for the comment, could rename the const to something like `EXPECTED_AUTOS_PER_WINDOW` since it's expected, not max.

2022-04-24 04:29 UTC, ChristopherJTrent reviewed
:lgtm:

2022-04-24 04:32 UTC, ayyaruq approved these changes

2022-04-24 04:32 UTC, merged