patch 610 data layers for ACTIONS + STATUSES
xivanalysis/xivanalysis pull request #1663
Opened 2022-04-11 11:56 UTC by suShirow

I'm surprised we didn't have this yet. 
Statuses layer file includes the duration change for SCH expedience, just to get the ball rolling. (Actually I was lazy to separate it sorry)

2022-04-11 12:02 UTC, ayyaruq requested changes
Looks like another file got included by accident, just kill that and gucci sushi.

2022-04-11 12:02 UTC, ayyaruq commented on src/parser/core/modules/ActionWindow/windows/ActionWindow.tsx
> +	* The captured windows.
Bruddah? It was correct before.

2022-04-11 12:11 UTC, suShirow commented on src/parser/core/modules/ActionWindow/windows/ActionWindow.tsx
> +	* The captured windows.
Oh no crossfire

2022-04-12 01:59 UTC, ayyaruq approved these changes

2022-04-12 01:59 UTC, merged