Speed up DeduplicateAoEStep
xivanalysis/xivanalysis pull request #1695
Opened 2022-04-29 22:04 UTC by skimmedsquare

Switch the implementation from using Array.find to a map for faster lookups.

Using https://xivanalysis.com/fflogs/LJkKTn8aWzPcxvZC/15/14 the time using Chromium's Performance tab goes from ~6s to ~14ms

2022-04-29 22:34 UTC, ChristopherJTrent commented on src/reportSources/legacyFflogs/eventAdapter/deduplicateAoE.ts
> +		const key = `${event.type}:${event.sequence}`
Minor style nit, we usually include an extra line break after constants and variables.
```suggestion
		const key = `${event.type}:${event.sequence}`
		
```

2022-05-04 18:16 UTC, skimmedsquare commented
Hmm, note to self, I should add some unit tests for this step prior to merge. Marking this back as a draft for now.

2022-05-08 08:54 UTC, skimmedsquare commented
Added unit tests and marked this as ready for review again, tested the unit tests on a `cherry-pick`ed branch and they currently pass.

```
 PASS  src/parser/core/__tests__/Dispatcher.ts
 PASS  src/parser/core/__tests__/filter.ts
 PASS  src/parser/core/__tests__/Analyser.ts
 PASS  src/data/__tests__/getDataBy.ts
 PASS  src/reportSources/legacyFflogs/eventAdapter/__tests__/deduplicateAoE.ts
 PASS  src/reportSources/legacyFflogs/__tests__/eventAdapter.ts
 PASS  src/parser/core/__tests__/Parser.js
 PASS  src/parser/core/modules/Gauge/__tests__/TimerGauge.ts (5.469 s)
 PASS  src/__tests__/Root.tsx (6.432 s)

Test Suites: 9 passed, 9 total
Tests:       99 passed, 99 total
Snapshots:   39 passed, 39 total
Time:        8.532 s, estimated 9 s
```

2023-05-21 20:20 UTC, AzariahAeroborn requested changes

2023-05-21 20:20 UTC, AzariahAeroborn commented on src/reportSources/legacyFflogs/eventAdapter/__tests__/deduplicateAoE.ts
> +				expect(results.filter(e => (e as Events['damage']).sequence != null).length).toEqual(1)
This assertion doesn't make sense to me.  I would expect an assertion that there are still 2 events with no sequence ID, and possibly an additional assertion that each event only has 1 target.  Instead this appears to be asserting that it deduplicated regular damage events?

2023-05-21 20:20 UTC, AzariahAeroborn commented on src/reportSources/legacyFflogs/eventAdapter/__tests__/deduplicateAoE.ts
> +				ensureOrder(results.map(e => e.timestamp))
This needs some additional logic to ensure that the two DOT events didn't get scrambled by the ordering, since their timestamps are both the same.

2023-05-21 20:20 UTC, AzariahAeroborn commented on src/reportSources/legacyFflogs/eventAdapter/__tests__/deduplicateAoE.ts
> +				expect(results.filter(e => (e as Events['heal']).sequence != null).length).toEqual(1)
See comments on DOT event test - same issue here.

2023-05-21 20:20 UTC, AzariahAeroborn commented on src/reportSources/legacyFflogs/eventAdapter/__tests__/deduplicateAoE.ts
> +				ensureOrder(results.map(e => e.timestamp))
See comments on damage event order test - same issue here.

2023-05-21 20:20 UTC, AzariahAeroborn commented on src/reportSources/legacyFflogs/eventAdapter/__tests__/deduplicateAoE.ts
> +				ensureOrder(results.map(e => e.timestamp))
See comments on damage event order test - similar issue here with the two execute events at timestamp 1.

2023-05-21 20:20 UTC, AzariahAeroborn commented on src/reportSources/legacyFflogs/eventAdapter/deduplicateAoE.ts
> +	private memo: Map<string, Event> = new Map<string, Event>()
style nit: I would prefer something like eventMap or something otherwise meaningful, rather than memo.  Not blocking on this comment.

2023-07-30 14:41 UTC, AkairyuGestalter commented
Superseded by #1876 in terms of functionality. If we still decide it's worth having the unit tests we can open a fresh PR for them at a later date. Closing.

2023-07-30 14:41 UTC, closed without merging