BLM - show tincture window
xivanalysis/xivanalysis pull request #1918
Opened 2023-10-12 04:47 UTC by noloerino

Resolves #1917

2023-10-14 16:30 UTC, AkairyuGestalter requested changes
I don't know why it hadn't occurred to me to add a Tinctures display to BLM before now...

Can you add a changelog entry for this? We want to have those for any end-user visible change, and you should take credit for your contribution!

2023-10-14 20:53 UTC, noloerino commented
Done, thanks for the reminder!

2023-10-17 03:02 UTC, AkairyuGestalter requested changes
One more nitpick: Can you drop the image resolution for your icon to something like 100-150px? These don't show particularly large anyways, so it's nice to have the files a bit smaller to save on memory/bandwidth

2023-10-18 00:04 UTC, AkairyuGestalter approved these changes

2023-10-18 00:04 UTC, merged