RDM: add the new 7.0 actions
xivanalysis/xivanalysis pull request #1993
Opened 2024-07-12 12:34 UTC by Hugmeir

## Pull request type

- [X] This is new functionality or an addition to existing functionality

## Pull request details

This MR is adding the four new RDM actions added in Dawntrail (`Jolt 3`, `Grand Impact`, `Vice of Thorns`, `Prefulgence`).  It's not changing the existing logic from EW, and it is not adding the related effects (`Thorned Flourish`, `Prefulgence Ready`, `Grand Impact Ready`) -- so this just fixes the timeline & GCD uptime, but does not mean DT RDM is fully supported.

## Testing / Validation

I'm a console player so I can't generate my own logs, but I did test it against this one:
https://www.fflogs.com/reports/6bkZFHrqdJztLYcK#fight=10&type=damage-done

Really, any RDM log from DT will suffice.

2024-07-12 23:40 UTC, AzariahAeroborn requested changes

2024-07-12 23:40 UTC, AzariahAeroborn commented on src/data/ACTIONS/root/RDM.ts
> +	},
Missing new actions: Enchanted Moulinet Deux and Trois (the additional hits of the AOE melee combo)

2024-07-13 12:50 UTC, AzariahAeroborn commented
I think we can close this in favor of #1999 - if you have any concerns, please let me know or feel free to comment on that PR with things you notice that are not correct.

2024-07-14 00:00 UTC, closed without merging

2024-07-14 00:01 UTC, AkairyuGestalter commented
Superseded by #1999