Dawntrail - Baseline updates for Scholar
xivanalysis/xivanalysis pull request #1994
Opened 2024-07-12 22:20 UTC by Mercwri

## Pull request type
- [X] This is a patch bump

## Pull request details

Supports baseline changes to the job introduced in Dawntrail, as the job did substantially change from Endwalker this really only consists of updating cooldown values and adding new abilities.

## Testing / Validation

Logs used for testing:  http://localhost:3000/fflogs/Fp91L3P6MRXQKnmA

## Job Maintenance
- [ ] I am active on the xivanalysis Discord and part of the job maintainers group for the job(s) in this PR
- [ ] I have collaborated with one or more job maintainers for the job(s) in this PR while developing it
- [ ] I prefer to receive any communications through GitHub only

2024-07-12 23:53 UTC, AzariahAeroborn requested changes

2024-07-12 23:53 UTC, AzariahAeroborn commented on yarn.lock
Would prefer to not have this change merge in with a job data file update, can you back it out of this PR and potentially open a separate PR for the update?

2024-07-12 23:53 UTC, AzariahAeroborn commented on src/data/ACTIONS/root/SCH.ts
> +		statusesApplied: ['BANEFUL_IMPACTION'],
Baneful Impaction isn't a combo skill - you don't lose the ability to cast it just because you do something else in between.

2024-07-12 23:53 UTC, AzariahAeroborn commented on src/parser/jobs/sch/index.js
> +		from: '7.0',
These data changes aren't sufficient to be ready for support - we should at least add some handling for making sure people are using Impact Imminent, handle the effects of Seraphism on Emergency Tactics

2024-07-13 12:46 UTC, AzariahAeroborn approved these changes, later dismissed

2024-07-13 12:49 UTC, AzariahAeroborn commented
Thanks for resolving those.  We do want to make sure that we appropriately recognize people who are assisting with the project, so can you please add a change log entry in the `/parser/SCH/changelog.tsx` file indicating that you're adding Dawntrail actions (or similar), and upload an avatar (max 100x100px / 100KB) to /src/data/avatar and add yourself to the /src/data/CONTRIBUTORS.ts file?

If you have any questions, please feel free to drop by our Discord and tag yourself with the Developer role.

2024-07-13 16:20 UTC, nonowazu commented
In addition to the changelog change, the only other thing I see that needs to be done for basic support is modifying `/parser/jobs/sch/index.js` to add supported patches:

```js
	supportedPatches: {
		from: '7.0',
		to: '7.0',
	},
```

2024-07-13 17:05 UTC, Mercwri commented
> In addition to the changelog change, the only other thing I see that needs to be done for basic support is modifying `/parser/jobs/sch/index.js` to add supported patches:
> 
> ```js
> 	supportedPatches: {
> 		from: '7.0',
> 		to: '7.0',
> 	},
> ```
> 
> EDIT: After the discussion on the channel, if you don't do the baneful impaction work, don't make this change. If you don't do it, I'll do it, so don't worry about it not getting done.

I was attempting look at the best way to implement that, but if you have a plan already go ahead. (thanks by the way)

2024-07-13 17:07 UTC, AzariahAeroborn approved these changes

2024-07-13 17:07 UTC, merged