[WHM] Track lost Divine Caress uses
xivanalysis/xivanalysis pull request #2031
Opened 2024-07-21 21:13 UTC by Dot-Inni

## Pull request type

- [x] This is new functionality or an addition to existing functionality
- [ ] This is a bugfix to existing functionality
- [ ] This is a patch bump

## Pull request details

- [ ] This is in response to a GitHub issue: *[Link to issue]*
- [ ] This is in response to a discussion or thread on Discord: *[Link to thread or start of discussion]*
- [x] The goal of this PR is detailed below:

	Tracking the lost uses of Divine Caress

## Testing / Validation

- [ ] The changes being implemented with this bugfix include comments that contain example log(s) to test with
  - [ ] I have submitted the example log(s) to the xivanalysis static on FFLogs for record keeping
- [x] I used the log(s) listed below to develop and test this bugfix:

   //https://www.fflogs.com/reports/tbXrQWDn3fawqz9g#fight=44&type=casts&source=759&translate=true

## Job Maintenance
- [x] I am active on the xivanalysis Discord and part of the job maintainers group for the job(s) in this PR
- [ ] I have collaborated with one or more job maintainers for the job(s) in this PR while developing it
- [ ] I prefer to receive any communications through GitHub only

2024-07-21 21:43 UTC, Dot-Inni commented
Ended up with some very minor fixes for various things that were stumbled upon while working on this module:

1.  Changing a wrong applied status in actions
2. Removing an unneccessary line in the index

2024-07-22 01:26 UTC, AzariahAeroborn requested changes
This PR needs a changelog entry, as it is adding new job analysis functionality.

2024-07-22 12:16 UTC, Dot-Inni commented
> This PR needs a changelog entry, as it is adding new job analysis functionality.

Added! Forgot that's a thing. #newExpansionThings

2024-07-22 18:55 UTC, AzariahAeroborn approved these changes

2024-07-22 18:55 UTC, merged