add link to CrowdIn in README.md
xivanalysis/xivanalysis pull request #978
Opened 2020-08-05 21:16 UTC by AzariahAeroborn

Start with a simple change, and then we can figure out if we want to add something to the i18n docs page or otherwise.

2020-08-07 23:18 UTC, KelosPelmand submitted a review, later dismissed
Looks good to me.  Most I might suggest would be some sort of "we only do officially supported languages", but the people that statement would target probably come straight to discord, so they wouldn't read the readme file.

2020-09-12 21:11 UTC, AzariahAeroborn commented
> I'm with Kelos, would be good to have a note about supported language and also have a list of what those languages are, prob with the English name, localised name, locale name, and maybe a flag because it's cool.

I added the English name.  Not certain of what the correct localised names would be, and they're not on our Crowdin project either.  I experimented with a couple options for flags but I don't think they're really worth the effort to try to style inline in markdown and emoji-flags don't display as flags when someone's viewing via Windows.

2020-10-01 01:26 UTC, ayyaruq requested changes
TIL emoji flags don't work in Windows, nice. Here's the localised strings for you.

2020-10-01 01:26 UTC, ayyaruq commented on README.md
> +- Korean
```suggestion
- Japanese (日本語)
- German (Deutsch)
- French (Français)
- Korean (한국어)
- Chinese Simplified (简体中文)
```

2020-10-01 01:47 UTC, ayyaruq approved these changes
Noice (ナイス)

2020-10-01 01:47 UTC, merged